FROM tomcat:9-jre17-temurin
COPY target/*.war /usr/local/tomcat/webapps/ROOT.war
WORKDIR /usr/local/tomcat
LABEL maintainer="HARRY"
EXPOSE $PORT
ENV CATALINA_OPTS="-Dserver.port=$PORT"
CMD ["sh", "-c", "sed -i 's/8080/'$PORT'/g' /usr/local/tomcat/conf/server.xml && catalina.sh run"]