[build]
builder = "NIXPACKS"

[deploy]
startCommand = "java -Dserver.port=$PORT -cp target/classes:target/dependency/* com.mt.HelloWorldServlet"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"