name: Maven Build

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    name: Build with Maven
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      # Step 3: Build project with Maven
      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      # Step 4: Upload artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: maven-artifact
          path: target/*.jar
