name: Maven Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  package:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'  # ✅ Improves performance by caching Maven dependencies

    - name: Build and test with Maven (with coverage)
      run: mvn -B clean test jacoco:report  # Run tests and generate coverage report
    
    - name: Display coverage summary
      run: |
        if [ -f target/site/jacoco/index.html ]; then
          echo "=== COVERAGE REPORT ==="
          echo "Instructions: $(grep -o 'Total[^<]*' target/site/jacoco/index.html | grep -o '[0-9]*%' | head -1 || echo 'N/A')"
          echo "Branches: $(grep -o 'Total[^<]*' target/site/jacoco/index.html | grep -o '[0-9]*%' | sed -n '2p' || echo 'N/A')"
          echo "Lines: $(grep -o 'Total[^<]*' target/site/jacoco/index.html | grep -o '[0-9]*%' | sed -n '3p' || echo 'N/A')"
          echo "Methods: $(grep -o 'Total[^<]*' target/site/jacoco/index.html | grep -o '[0-9]*%' | sed -n '4p' || echo 'N/A')"
          echo "Classes: $(grep -o 'Total[^<]*' target/site/jacoco/index.html | grep -o '[0-9]*%' | tail -1 || echo 'N/A')"
          echo "Full report available in artifacts"
        else
          echo "No coverage report found"
        fi
    
    - name: Package with Maven
      run: mvn -B package -DskipTests  # Package after tests

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/maven-web-app:latest .

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/maven-web-app:latest

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ secrets.DOCKER_USERNAME }}/maven-web-app:latest'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: maven-artifacts
        path: target/
    
    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: coverage-reports
        path: target/site/jacoco/
