name: Maven Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  package:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Package with Maven
      run: mvn package
    
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
       SONAR_TOKEN: ${SONAR_TOKEN}

     
    
    - name: Build Docker image
      run: docker build -t maven-web-app:latest .
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'maven-web-app:latest'
        format: 'sarif'
        output: 'trivy-results.sarif'
    
    - name: Upload Trivy scan results
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: maven-artifacts
        path: target/ 